name: Node.js CI

on:
  push:
    branches: ['deploy']
  pull_request:
    branches: ['deploy']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Move public folder
        run: |
          if [ -d "public" ]; then
            mkdir -p ~/cicd/_temp/travel/public
            mv public ~/cicd/_temp/travel/
          else
              echo "Public folder does not exist; so Nothing to move."
          fi

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm i

      - name: Build Project
        run: pnpm build

      - name: Restore public folder
        run: |
          if [ -d "~/cicd/_temp/travel/public/" ]; then
            mv ~/cicd/_temp/travel/public/ public/
          else
            echo "Public folder does not exist; so nothing to restore"
          fi

      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Restart Pm2
        run: |
          export HOME="~/cicd"
          pm2 restart travel --update-env